# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="gentoo"
#ZSH_THEME="alanpeabody"
ZSH_THEME="clean"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias gds='git diff --cached'

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git docker zsh-syntax-highlighting ssh-agent kubectl kops)
plugins+=(terraform)

zstyle :omz:plugins:ssh-agent agent-forwarding on
# zstyle :omz:plugins:ssh-agent lifetime 6h
zstyle :omz:plugins:ssh-agent identities id_rsa mgmt2.id_rsa

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export GOPATH=$HOME/Projects/go
#export SCALAPATH=$HOME/scala

export PATH=~/bin:~/.composer/vendor/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin
export PATH="$PATH:/usr/local/go/bin:$GOPATH/bin:$HOME/.cargo/bin"
export PATH="$HOME/.phpenv/bin:$PATH"
export RUST_SRC_PATH=~/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src

export EDITOR=/usr/local/bin/nvim
export AWS_PROFILE=sts

fancy-ctrl-z () {
    if [[ $#BUFFER -eq 0 ]]; then
        BUFFER="fg"
        zle accept-line
    else
        zle push-input
        zle clear-screen
    fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z

#eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"
eval "$(phpenv init -)"

#source ~/.config/zsh/completions.d/*.sh

function gitlab() {
    SSH_AUTH_SOCK=$HOME/.sekey/ssh-agent.ssh git "$@"
}

function fp() {
    env SSH_AUTH_SOCK=$HOME/.sekey/ssh-agent.ssh "$@"
}

alias k=kubectl
alias ks="kubectl -n kube-system"
alias kw="kubectl get events --watch"
alias kga="kubectl get all"
alias ka="kubectl apply -f"

alias icatr="kitty +kitten icat"
alias icat="icatr --align right --place \$(tput cols)x\$(((\$(tput lines) - 10)))@0x0"
alias scoot="icat ~/Pictures/1016091707.jpg"
alias tp="terraform plan -out=plan.out"

alias dvm="docker run -it --privileged --pid=host debian:stretch-slim nsenter -t 1 -m -u -n -i sh"
